openapi: 3.0.0
info:
  title: Rana App Api
  description: It is used to Rana App Api.
  version: 1.0 
  
servers:
  - url: http://localhost:8850/
    description:  Local server 
  - url: https://prod.com/
    description:  Pre Production server
  - url: https://test.com/
    description:  Production server
  

 
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
# 2) Apply the security globally to all operations
security:
  - bearerAuth: [] 
paths:
  /createUser:
    post:
      tags:
        - User API   
      post:
      requestBody:
        required: true
        content:
          # multipart/form-data:
           application/json:
            schema:
              type: object
              properties: 
                name:         
                  type: string
                  example: "sridhar"  
                phone:       
                  type: string
                  example: "9491908107" 
                email:
                  type: string
                  example: "sridhar@gmail.com"
                password:
                  type: string 
                  example: "Sridhar1247@"
      responses:
        '200':
          description: Registration is Success. 
        '400':
          description: User Details is Required.
        '404':
          description: Server error.
        default:
          description: Unexpected error
  /userLogin:
    post:
      tags:
        - User API    
      post:
      requestBody:
        required: true
        content:
           application/json:
            schema:
              type: object
              properties: 
                email:
                  type: string
                  example: "sridhar@gmail.com"
                password:
                  type: string 
                  example: "Sridhar1247@"
      responses:
        '200':
          description: Registration is Success. 
        '400':
          description: User Details is Required.
        '404':
          description: Server error.
        default:
          description: Unexpected error
  /user/info:
    post:
      tags:
        - User API    
      post:
      requestBody:
        required: true
        content:
           application/json:
            schema:
              type: object
              properties: 
                email:
                  type: string
                  example: "sridhar@gmail.com"
      responses:
        '200':
          description: Registration is Success. 
        '400':
          description: Invalid Credentials
        '404':
          description: Server error.
        default:
          description: Unexpected error  
  /allUserDetails:
    get:
      tags:
        - User API    
      responses:
        '200':
          description: Registration is Success. 
        '400':
          description: User Details is Required.
        '404':
          description: Server error.
        default:
          description: Unexpected error
  /updateUser:
    put:
      tags:
        - User API    
      post:
      requestBody:
        required: true
        content:
          # multipart/form-data:
           application/json:
            schema:
              type: object
              properties: 
                id:
                  type: string
                  example: "6451cf1d52a4adebd8a56401"
                name:
                  type: string 
                  example: sridhar
      responses:
        '200':
          description: Registration is Success. 
        '400':
          description: User Details is Required.
        '404':
          description: Server error.
        default:
          description: Unexpected error
  /forgot/password:
    post:
      tags:
        - User API    
      post:
      requestBody:
        required: true
        content:
          # multipart/form-data:
           application/json:
            schema:
              type: object
              properties: 
                email:
                  type: string
                  example: "sridhar@gmail.com"
      responses:
        '200':
          description: Registration is Success. 
        '400':
          description: User Details is Required.
        '404':
          description: Server error.
        default:
          description: Unexpected error
  /reset/password/{token}:
    post:
      tags:
        - User API    
      post:
      requestBody:
        required: true
        content:
          # multipart/form-data:
           application/json:
            schema:
              type: object
              properties: 
                email:
                  type: string
                  example: "sridhar@gmail.com"
      responses:
        '200':
          description: Registration is Success. 
        '400':
          description: User Details is Required.
        '404':
          description: Server error.
        default:
          description: Unexpected error
  /delete/user/{userId}:
    delete:
      tags:
        - User API 
    parameters:
    - in: path
      name: userId
      required: true
      schema:
        type: integer       
      responses:
        '200':
          description: Registration is Success. 
        '400':
          description: User Details is Required.
        '404':
          description: Server error.
        default:
          description: Unexpected error
  /follow:
    put:
      tags:
        - User API    
      post:
      requestBody:
        required: true
        content:
          # multipart/form-data:
           application/json:
            schema:
              type: object
              properties: 
                followId:
                  type: string
                  example: "6451cf1d52a4adebd8a56401"
      responses:
        '200':
          description: Registration is Success. 
        '400':
          description: User Details is Required.
        '404':
          description: Server error.
        default:
          description: Unexpected error
  /unfollow:
    put:
      tags:
        - User API    
      post:
      requestBody:
        required: true
        content:
          # multipart/form-data:
           application/json:
            schema:
              type: object
              properties: 
                followId:
                  type: string
                  example: "6451cf1d52a4adebd8a56401"
      responses:
        '200':
          description: Registration is Success. 
        '400':
          description: User Details is Required.
        '404':
          description: Server error.
        default:
          description: Unexpected error
        paths:
  /create/movie:
    post:
      tags:
        - Movies API   
      post:
      requestBody:
        required: true
        content:
          multipart/form-data:
          #  application/json:
            schema:
              type: object
              properties: 
                name:         
                  type: string
                  example: "sridhar"  
                phone:       
                  type: string
                  example: "9491908107" 
                email:
                  type: string
                  example: "sridhar@gmail.com"
                password:
                  type: string 
                  example: "Sridhar1247@"
      responses:
        '200':
          description: Registration is Success. 
        '400':
          description: User Details is Required.
        '404':
          description: Server error.
        default:
          description: Unexpected error  
  /update/movie:
    put:
      tags:
        - Movies API   
      post:
      requestBody:
        required: true
        content:
          multipart/form-data:
          #  application/json:
            schema:
              type: object
              properties: 
                name:         
                  type: string
                  example: "sridhar"  
                phone:       
                  type: string
                  example: "9491908107" 
                email:
                  type: string
                  example: "sridhar@gmail.com"
                password:
                  type: string 
                  example: "Sridhar1247@"
      responses:
        '200':
          description: Registration is Success. 
        '400':
          description: User Details is Required.
        '404':
          description: Server error.
        default:
          description: Unexpected error
        paths:
  /create/reel:
    post:
      tags:
        - Reels API   
      post:
      requestBody:
        required: true
        content:
          # multipart/form-data:
           application/json:
            schema:
              type: object
              properties: 
                videoUrl:         
                  type: string
                  example: "https://about.instagram.com/features/reels"  
                share:       
                  type: string
                  example: "facebook,instagram" 
                tags:
                  type: string
                  example: "movies"
      responses:
        '200':
          description: Reels Successfully Created. 
        '400':
          description: reels Details is Required.
        '404':
          description: Server error.
        default:
          description: Unexpected error
  /allReelDetails:
    get:
      tags:
        - Reels API    
      responses:
        '200':
          description: Registration is Success. 
        '400':
          description: User Details is Required.
        '404':
          description: Server error.
        default:
          description: Unexpected error  
 