openapi: 3.0.0
info:
  title: Code Improve API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0 
  

servers:
  - url: http://localhost:8081/
    description:  Local server 
  - url: https://prod.com/
    description:  Pre Production server
  - url: https://test.com/
    description:  Production server
  

 
components:
  securitySchemes:
    ApiTokenss:        # arbitrary name for the security scheme
          
      type: http
      scheme: bearer
    
    ApiKey:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: apikey
      
paths:
  # /users/detail/{userId}:
  #   get:
  #     security:
  #      - ApiTokenss: []
  #      - ApiKey: []
  #     summary: Returns a user details by ID.
  #     parameters:
  #       - name: userId
  #         in: path
  #         required: true
  #         description: Parameter description in CommonMark or HTML.
  #         schema:
  #           # type : integer
  #           # format: int64
  #           type: string
  #           example: "Users String"
  #           minimum: 1
  #     responses: 
  #       '200':
  #         description: OK
  

  paths:
  /users/list:
    post:
      tags:
        - Create User API 
      summary: Create user api.     
      post:
      requestBody:
        required: true
        content:
          # multipart/form-data:
           application/json:
            schema:
              type: object
              properties: 
                name:         
                  type: string
                  example: "sridhar"  
                phone:       
                  type: string
                  example: "9491908107" 
                email:
                  type: string
                  example: "sridhar@gmail.com"
                password:
                  type: string 
                  example: "Sridhar1247@"
      responses:
        '200':
          description: Registration is Success. 
        '400':
          description: User Details is Required.
        '404':
          description: Server error.
        default:
          description: Unexpected error

paths:
  /users/list:
    post:
      tags:
        - Login API 
      summary: Returns a user list.     
      post:
      requestBody:
        required: true
        content:
          # multipart/form-data:
           application/json:
            schema:
              type: object
              properties: 
                name:         
                  type: string
                  example: "sridhar"  
                phone:       
                  type: string
                  example: "9491908107" 
                email:
                  type: string
                  example: "sridhar@gmail.com"
                password:
                  type: string 
                  example: "Sridhar1247@"
      responses:
        '200':
          description: Registration is Success. 
        '400':
          description: User Details is Required.
        '404':
          description: Server error.
        default:
          description: Unexpected error
  
  